package com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.Repository;

import com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.JSONdb.JSONrepository;

public interface InventarioEquipaggiatoRepository <InventarioEquipaggiatoEntity> extends JSONrepository<InventarioEquipaggiatoEntity> {
}
