package com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.Repository;

import com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.JSONdb.JSONrepository;

public interface OggettoBattleGroundRepository<OggettoBattleGroundEntity> extends JSONrepository<OggettoBattleGroundEntity> {
}
