package com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.Repository;

import com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.JSONdb.JSONrepository;

public interface ProtezioniIndossabiliRepository <ProtezioniIndossabiliEntity> extends JSONrepository<ProtezioniIndossabiliEntity> {
}
