package com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.Repository;

import com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.JSONdb.JSONrepository;
import com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.Requests.RazzaNewJSONreq;
import com.adryanSoftwares.ilGiocoDelTizioCheStaConAdryan.responses.RazzaNewJSONresp;

public interface RazzaRepository extends JSONrepository<RazzaNewJSONreq, RazzaNewJSONresp> {
}
